services:

  mysql:
    image: mysql:8.4
    container_name: employee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - employee-network

  employee-app:
    image: employee-app:9
    container_name: employee-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devopslab
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8080"
    networks:
      - employee-network

volumes:
  mysql-data:

networks:
  employee-network:
    driver: bridge
