spring:
  application:
    name: employee-app

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devopslab}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
